// Code generated by "stringer -type itemType -trimprefix item"; DO NOT EDIT.

package yacc

import "strconv"

const _itemType_name = "ErrorEOFCommentPctDoublePctIdentIdentColonColonLiteralExprPipeNL"

var _itemType_index = [...]uint8{0, 5, 8, 15, 18, 27, 32, 42, 47, 54, 58, 62, 64}

func (i itemType) String() string {
	if i < 0 || i >= itemType(len(_itemType_index)-1) {
		return "itemType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _itemType_name[_itemType_index[i]:_itemType_index[i+1]]
}
